language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE testdb;'
notifications:
  slack: unchill201903fsf2:VB8jckcFbYELj5CcOFEAIokX
